import { useEffect, useState, type FormEvent } from 'react';
import { client, errorMessage, publicCms } from '@/lib/cms';
export type Trace={id:string;entry_id:string;name:string;body:string;status:'pending'|'approved'|'hidden';author_reply:string|null;author_replied_at:string|null;created_at:string;updated_at:string};
const stamp=(v:string)=>new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export default function Traces({entryId}:{entryId:string}){
 const [traces,setTraces]=useState<Trace[]>([]),[name,setName]=useState(''),[body,setBody]=useState(''),[anonymous,setAnonymous]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let alive=true;if(!publicCms)return;publicCms.from('cms_traces').select('*').eq('entry_id',entryId).eq('status','approved').order('created_at',{ascending:false}).then(({data,error})=>{if(!alive)return;if(error)setError(errorMessage(error));else setTraces((data||[]) as Trace[])});return()=>{alive=false}},[entryId]);
 async function submit(e:FormEvent){e.preventDefault();if(!publicCms||!body.trim())return;setBusy(true);setError('');setNotice('');const {error}=await publicCms.from('cms_traces').insert({entry_id:entryId,name:anonymous||!name.trim()?'Anonymous':name.trim(),body:body.trim()});setBusy(false);if(error){setError(errorMessage(error));return}setBody('');setName('');setAnonymous(false);setNotice('Your trace was left behind. It will appear after moderation.')}
 return <section className="traces" aria-labelledby="traces-title"><header><div><span>LEAVE SOMETHING BEHIND</span><h2 id="traces-title">Traces <small>{traces.length}</small></h2></div></header><form className="trace-form" onSubmit={submit}><label>Leave a trace<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="A thought, a memory, or something this made you think of."/></label><div><input maxLength={80} disabled={anonymous} value={name} onChange={e=>setName(e.target.value)} placeholder="Name (optional)"/><label className="trace-anon"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/> Anonymous</label><button disabled={busy||!body.trim()}>{busy?'Leaving…':'Submit Trace →'}</button></div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}</form><div className="trace-list">{traces.map(t=><article key={t.id}><header><strong>{t.name}</strong><time>{stamp(t.created_at)}</time></header><p>{t.body}</p>{t.author_reply&&<div className="trace-author-reply"><header><strong>DEMICORPSE</strong><span>AUTHOR</span>{t.author_replied_at&&<time>{stamp(t.author_replied_at)}</time>}</header><p>{t.author_reply}</p></div>}</article>)}</div></section>
}
export function TraceAdmin(){
 const [items,setItems]=useState<Trace[]>([]),[filter,setFilter]=useState<'pending'|'approved'|'hidden'>('pending'),[replying,setReplying]=useState<string|null>(null),[reply,setReply]=useState('');
 const load=async()=>{const {data}=await client().from('cms_traces').select('*').eq('status',filter).order('created_at',{ascending:false});setItems((data||[]) as Trace[])};
 useEffect(()=>{void load()},[filter]);
 const update=async(id:string,values:Partial<Trace>)=>{await client().from('cms_traces').update({...values,updated_at:new Date().toISOString()}).eq('id',id);await load()};
 return <section className="trace-admin"><div className="trace-admin-tabs">{(['pending','approved','hidden'] as const).map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}</button>)}</div>{!items.length?<p className="cms-muted">No {filter} traces.</p>:items.map(t=><article key={t.id}><div><strong>{t.name}</strong><time>{stamp(t.created_at)}</time><p>{t.body}</p></div><div className="cms-actions">{t.status!=='approved'&&<button className="cms-button" onClick={()=>void update(t.id,{status:'approved'})}>Approve</button>}{t.status!=='hidden'&&<button className="cms-button" onClick={()=>void update(t.id,{status:'hidden'})}>Hide</button>}<button className="cms-button" onClick={()=>{setReplying(replying===t.id?null:t.id);setReply(t.author_reply||'')}}>Reply</button></div>{replying===t.id&&<div className="trace-reply-editor"><textarea value={reply} maxLength={2000} onChange={e=>setReply(e.target.value)} placeholder="Reply as DemiCorpse…"/><button className="cms-button cms-primary" onClick={()=>void update(t.id,{author_reply:reply.trim()||null,author_replied_at:reply.trim()?new Date().toISOString():null,status:'approved'}).then(()=>{setReplying(null);setReply('')})}>Publish reply</button></div>}</article>)}</section>
}
